version: "3.8"
services:
  metabase:
    image: metabase/metabase:latest # Pulls the latest Metabase image
    container_name: metabase # Names the container for easy reference
    ports:
      - "3000:3000" # Exposes Metabase on host port 3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db # Uses a file-based H2 database stored in a volume
    volumes:
      - ./metabase-data:/metabase-data # Persists Metabase data on the host filesystem

  nginx:
    image: nginx:latest # Pulls the latest Nginx image
    container_name: nginx # Names the container for easy reference
    depends_on:
      - metabase # Ensures Metabase starts before Nginx
    ports:
      - "8080:80" # Maps host port 8080 to container port 80 (random choice)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mounts our custom Nginx config as read-only
